# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2008-06-24 22:06+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: gpg-open:27
#, python-format
msgid "Error: No Armored File"
msgstr "Unable to read armored file %s!"

#: gpg-open:28
#, python-format
msgid "Error: No Username"
msgstr "Unable to read username for user ID %s!"

#: gpg-open:29
msgid "Error: No Inputfile"
msgstr "No input file definede!"

#: gpg-open:30
msgid "Error: No Addressee"
msgstr "Unable to read encryption assignee!"

#: gpg-open:31
msgid "Unable to parse valid username from output!"
msgstr ""

#: gpg-open:32
#, python-format
msgid "Runtime Exception: %s"
msgstr ""

#: gpg-open:33
#, python-format
msgid "Undefined user ID %s!"
msgstr ""

#: gpg-open:58
#, python-format
msgid "Calling command '%s' ..."
msgstr ""

#: gpg-open:64
#, python-format
msgid "Process call failed with error code (%s):"
msgstr ""

#: gpg-open:149
#, python-format
msgid "Multiple possible users. Need to choose one of %s."
msgstr ""

#: gpg-open:163
msgid "Choose User"
msgstr ""

#: gpg-open:164
msgid ""
"This file is encrypted to multiple users. Please choose the one you want to "
"use for decryption:"
msgstr ""

#: gpg-open:165
msgid "User"
msgstr ""

#: gpg-open:175
#, python-format
msgid "Chosen user is %s."
msgstr ""

#: gpg-open:184
msgid "Authentication"
msgstr ""

#: gpg-open:185
#, python-format
msgid "Please enter password for user %s:"
msgstr ""

#: gpg-open:200
#, python-format
msgid "Created temporary directory %s."
msgstr ""

#: gpg-open:210
#, python-format
msgid "Temporary file will be %s."
msgstr ""

#: gpg-open:218
msgid "Unable to decrypt file!"
msgstr ""

#: gpg-open:225
msgid "Unable to calculate MD5 hash sum!"
msgstr ""

#: gpg-open:228
#, python-format
msgid "Opening temorary file %s ..."
msgstr ""

#: gpg-open:235
#, python-format
msgid "Sub process exited with error (%s)!"
msgstr ""

#: gpg-open:237
msgid "Unable to open file!"
msgstr ""

#: gpg-open:240
#, python-format
msgid ""
"Process 'gnome-open' finished very quicklt (%s seconds). Maybe the target "
"application was forked internally?"
msgstr ""

#: gpg-open:245
msgid "Removing temporary data ..."
msgstr ""

#: gpg-open:296
msgid "Temporary file modified. Encrypting ..."
msgstr ""

#: gpg-open:299
msgid "Temporary file unmodified."
msgstr ""

#: gpg-open:302
msgid "Process exited with exception:"
msgstr ""

#: gpg-open:308
msgid "User cancellation."
msgstr ""
